!config:

# Specifies IP to listen to for svn:// connections
# Default: 0.0.0.0
#
# host: 0.0.0.0

# Specifies port number to listen to for svn:// connections
# Default: 3690
#
# port: 3690

# Subversion realm name. Subversion uses this for credentials caching
# Default: repository UUID
#
# realm: git-as-svn realm

# If enabled, git-as-svn compresses wire traffic
# Default: true
#
# compressionEnabled: true

# If enabled, git-as-svn indexed repositories in parallel during startup
# This results in higher memory usage so may require adjustments to JVM memory options
# Default: true
#
# parallelIndexing: true

# Sets cache location
cacheConfig: !persistentCache
  path: /var/cache/git-as-svn/git-as-svn.mapdb

repositoryMapping: !listMapping
  repositories:
    example:
      acl:
        groups:
          - name: developers
            users:
              - test

        access:
          - path: /
            # Use 'asterisk' (*) to allow access for all users
            # use 'at' (@) for groups
            allowed:
              - '@developers'
      repository:
        # Allowed pushers:
        # !pushEmbedded - use embedded push (fast, no dependencies)
        #   update: "update"            - name of update hook
        #   preReceive: "pre-receive"   - name of pre-receive hook
        #   postReceive: "post-receive" - name of post-receive hook
        # !pushNative {} - use console git for push (hooks worked, can be slow on some commits, require installed console git)
        pusher: !pushEmbedded
          update: update
          preReceive: pre-receive
          postReceive: post-receive
        # Allowed create modes:
        # - ERROR - exit with error, if repository not exists
        # - EMPTY - create empty repository
        # - EXAMPLE - create repository with example data
        createMode: EXAMPLE
        branches:
          - master
        path: /var/git/repositories/example.git
        renameDetection: true

shared:
  # Submodule list.
  # You can define extra submodule path. Every path defined in "repositories" already included in submodule list.
  - !submodules [
  ]
  # Web server settings.
  # This web server used for some additional functionality like Git LFS support.
  # Subversion WebDAV access (via http/https) IS NOT SUPPORTED now.
  - !web
    # baseUrl: http://git-as-svn.local/
    listen:
      - !http
        host: localhost
        port: 8123
        # Use X-Forwarded-* headers
        forwarded: true
  # Git LFS server
  - !localLfs
    # Secret token for git-lfs-authenticate script
    # secretToken:
    path: /var/git/lfs

# Simple in-memory user database
userDB: !localUsers
  users:
    - username: test
      # Clear-text password is required to perform CRAM-MD5 authentication
      password: test
      # Email and real name are used to create Git commits
      email: test@noreply.fake
      realName: Test User

# Authenticates users against LDAP server
#
#userDB: !ldapUsers

  # LDAP server URL
  # It usually specifies the domain name of the directory server to connect to,
  # and optionally the port number and distinguished name (DN) of the required root naming context.
  # For secure connections, use ldaps://
  #
  # connectionUrl: ldap://localhost:389/ou=groups,dc=mycompany,dc=com

  # Optional path to LDAP SSL certificate file for secure LDAP connections
  #
  # ldapCertPem: ldap.pem

  # Pattern specifying the LDAP search filter to use after substitution of the username.
  #
  # searchFilter: (&(objectClass=person)(objectClass=user))

  # LDAP bind configuration. git-as-svn accesses LDAP both on behalf of itself for checking that user is found by search filter
  # and on behalf of user to test that user can successfully authenticate against LDAP server

  # Performs SASL ANONYMOUS bind as described in RFC 4505
  # This is default bind type.
  #
  # bind: !ANONYMOUS {}

  # Performs SASL CRAM-MD5 bind as described in draft-ietf-sasl-crammd5
  #
  # bind: !CRAMMD5
  #   authenticationID: <required>
  #   password: <required>

  # Performs SASL DIGEST-MD5 bind as described in RFC 2831
  #
  # bind: !DIGESTMD5
  #   authenticationID: <required>
  #   authorizationID: <optional>
  #   password: <required>
  #   realm: <optional>

  # Performs SASL EXTERNAL bind as described in RFC 4422
  #
  # bind: !EXTERNAL
  #   authenticationID: <optional>

  # Performs SASL PLAIN bind as described in RFC 4616
  #
  # bind: !PLAIN
  #   authenticationID: <required>
  #   authorizationID: <optional>
  #   password: <required>

  # Performs LDAPv3 simple bind operation
  #
  # bind: !Simple
  #   bindDn: <optional>
  #   password: <optional>

  # LDAP attribute, containing user login.
  #
  # loginAttribute: uid

  # LDAP attribute, containing user name.
  #
  # nameAttribute: name

  # LDAP attribute, containing user email.
  #
  # emailAttribute: mail
