language: java
sudo: true
jdk:
- oraclejdk8
addons:
  apt:
    packages:
    - fop
    - docbook-xsl
    - protobuf-compiler
before_install:
- sudo apt-get install -qq gnome-doc-utils
install:
- ./gradlew assemble
script:
- docbook/update.sh
- ./gradlew check
before_deploy:
- ./gradlew assembleDist
deploy:
  provider: releases
  api-key:
    secure: DOfUgYJSdDiRIjgULtOxR0jdvkxuXPn+4Q+UGYtnQNiov7hAJ6VbdQpGSczi0ik/RLzf51NuBJm4PuFGVy5sexeJuw4iUEa+gnJlDglJI/UHiHcr+E4HJnTUweAHTiHGADm2qyhyg3+n0D4pZ8m2j86UvNImZWYcPUwup0lul4U=
  file_glob: true
  file:
    - build/distributions/git-as-svn*
    - build/distributions/*.pdf
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
