language: java
sudo: false
jdk:
- oraclejdk8
env:
  global:
    secure: "WBJI+q1QXLSPhJwHEwgY1dec7dpm7Wdw1vinQa1G6uaoq08yt/+SXRw4ID0QkGzZhcvrNI4/nYzb2b6JS9o5KzE+Yu/8Wp7Gw5LWSRwwj5k1yKt7f2wkvxHkNwUEmwQ2VFIf9WFmtcQsaMomre3hIYuS67i7900ICKm1vNJh4lc="
addons:
  apt:
    packages:
    - protobuf-compiler
    - gnome-doc-utils
install:
- ./gradlew assemble
script:
- ./gradlew check
before_deploy:
- ./gradlew assembleDist
after_success: |
  [ $TRAVIS_BRANCH = master ] &&
  [ $TRAVIS_PULL_REQUEST = false ] &&
  pip install ghp-import --user $USER &&
  $HOME/.local/bin/ghp-import -n build/doc &&
  git push -qf https://${GH_TOKEN}@github.com/${TRAVIS_REPO_SLUG}.git gh-pages
deploy:
  provider: releases
  api-key:
    secure: DOfUgYJSdDiRIjgULtOxR0jdvkxuXPn+4Q+UGYtnQNiov7hAJ6VbdQpGSczi0ik/RLzf51NuBJm4PuFGVy5sexeJuw4iUEa+gnJlDglJI/UHiHcr+E4HJnTUweAHTiHGADm2qyhyg3+n0D4pZ8m2j86UvNImZWYcPUwup0lul4U=
  file_glob: true
  file:
    - build/distributions/git-as-svn*
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
