language: java
jdk:
 - oraclejdk8
before_deploy:
 - ./gradlew deployZip
deploy:
  provider: releases
  api-key: os.environ["DEPLOY_TOKEN"]
  file: build/distributions/git-as-svn.zip
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
