language: java
sudo: false
env:
  global:
    secure: "WBJI+q1QXLSPhJwHEwgY1dec7dpm7Wdw1vinQa1G6uaoq08yt/+SXRw4ID0QkGzZhcvrNI4/nYzb2b6JS9o5KzE+Yu/8Wp7Gw5LWSRwwj5k1yKt7f2wkvxHkNwUEmwQ2VFIf9WFmtcQsaMomre3hIYuS67i7900ICKm1vNJh4lc="
addons:
  apt:
    packages:
    - build-essential
    - fakeroot
    - debhelper
    - gnome-doc-utils
install:
- ./gradlew assemble
script:
- ./gradlew check
before_deploy:
- ./gradlew assembleDist
deploy:
  - provider: releases
    api-key:
      secure: DOfUgYJSdDiRIjgULtOxR0jdvkxuXPn+4Q+UGYtnQNiov7hAJ6VbdQpGSczi0ik/RLzf51NuBJm4PuFGVy5sexeJuw4iUEa+gnJlDglJI/UHiHcr+E4HJnTUweAHTiHGADm2qyhyg3+n0D4pZ8m2j86UvNImZWYcPUwup0lul4U=
    file_glob: true
    file:
      - build/distributions/git-as-svn*
    skip_cleanup: true
    on:
      tags: true
  - provider: script
    script: deploy/deploy.manual.sh
    skip_cleanup: true
    on:
      branch: master
  - provider: script
    script: deploy/deploy.debian.sh
    skip_cleanup: true
    on:
      tags: true
