language: java
jdk:
 - oraclejdk8
before_deploy:
 - gradle deployZip
deploy:
  provider: releases
  file: build/distributions/git-as-svn.zip
  skip_cleanup: true
  on:
    tags: true
    all_branches: true
